# Generated by Django 3.2.9 on 2021-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lezzet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
