# Generated by Django 3.2.9 on 2021-12-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0003_alter_lezzet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lezzet',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
