# Generated by Django 4.0 on 2021-12-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lezzet',
            name='image',
            field=models.ImageField(upload_to='hamburgers'),
        ),
    ]
