# Generated by Django 3.2.9 on 2021-12-16 12:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0006_alter_lezzet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lezzet',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
