# Generated by Django 3.2.9 on 2021-12-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0007_alter_lezzet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
