# Generated by Django 3.2.9 on 2021-12-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0008_auto_20211219_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='service',
        ),
    ]
