# Generated by Django 3.2.9 on 2021-12-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0010_auto_20211219_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='home',
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
