# Generated by Django 3.2.9 on 2021-12-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LezzET', '0012_home_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='services',
            name='subtitle',
        ),
    ]
